---
# tasks file for open_vm_tools

- name: Include distribution specific variables
  include_vars: "{{ ansible_distribution }}.yml"
  tags: open_vm_tools

- include: CentOS.yml
  when: ansible_distribution == "CentOS"
  tags: open_vm_tools

- include: Ubuntu.yml
  when: ansible_distribution == "Ubuntu"
  tags: open_vm_tools
