---
# tasks file for open_vm_tools

- name: Include distribution specific variables
  include_vars: "{{ ansible_distribution }}.yml"
  tags: open_vm_tools

- include: CentOS.yml
  when: ansible_distribution == "CentOS"
  tags: open_vm_tools

- include: Ubuntu.yml
  when: ansible_distribution == "Ubuntu"
  tags: open_vm_tools

- name: Ensure open-vm-tools service is started and enabled on boot
  service: name={{ open_vm_tools_service_name }} state=started enabled=yes
  tags: open_vm_tools
